name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: your-dockerhub-username/your-repo-name
      IMAGE_TAG: latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build with Maven
        run: |
          echo "===== Java Version ====="
          java -version
          echo "===== Maven Version ====="
          mvn -v
          mvn clean package \
            -Dmaven.compiler.source=17 \
            -Dmaven.compiler.target=17 \
            -Dmaven.compiler.fork=true

      - name: Build Docker Image
        run: |
          IMAGE_URI=${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          docker build -t $IMAGE_URI .

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_URI=${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          docker push $IMAGE_URI
